export default [
    "Yakın zamanda sosyal medyada neler olup bittiği hakkında oldukça fazla düşünüyorum.",
    "Yapmam gereken bir iş varsa öncesinde sosyal medyayı kontrol ederim.",
    "Belli bir süre sosyal medyaya girmediğimde sosyal medyaya girme düşüncesi zihnimi meşgul eder.",
    "Hayatımın sosyal medya olmadan sıkıcı, boş ve zevksiz olacağını düşünüyorum.",
    "İnternete bağlı değilken yoğun bir şekilde sosyal medyaya girmeyi düşünürüm.",
    "Sosyal medyada neler olup, bittiğini merak ederim.",
    "Sosyal medyada düşündüğümden daha fazla zaman geçirdiğim olur.",
    "Sosyal medya ile bağlantımı kesmeye karar verdiğimde kendi kendime birkaç dakika daha derim.",
    "Sosyal medyayı uzun süre kullanmaktan asla vazgeçemem.",
    "Sosyal medyayı, planladığımdan daha fazla kullandığım olur.",
    "Sosyal medyayı kullanırken zamanın nasıl geçtiğini anlayamam.",
    "Sosyal medya ile eylemlere oyun, sohbet, fotoğraflara bakmak, vs.) uzun süreler ayırırım.",
    "Kişisel problemlerimi unutmak için sosyal medya kullanırım.",
    "Kendimi yalnız hissettiğim zamanlarda sosyal medyada vakit geçiririm.",
    "Yaşamımdaki olumsuz düşüncelerden kurtulmak için sosyal medyada gezinmeyi tercih ederim.",
    "Problemlerimden ve bunaldığımda sığındığım en iyi yer sosyal medyadır.",
    "Sosyal medya kullandığım süre boyunca her şeyi unuturum.",
    "Sosyal medya kullanımını durdurmaya çalışıp başaramadığım olur.",
    "Sosyal medya kullanımını denetim altına almak için yoğun bir istek duyarım.",
    "Sosyal medya kullanımını bırakmak için sonuç vermeyen çabalar gösteririm.",
    "Sosyal medya kullanımını denetim altına almak için sonuç vermeyen çabalar gösteririm.",
    "Sosyal medyada harcadığım zamanı azaltmaya çalışır, başarısız olurum.",
    "Mesleğime çalışanlarıma olumsuz bir etki yapmasına rağmen sosyal medyayı daha fazla kullanırım.",
    "Sosyal medyadan dolayı hobilerime, boş zaman ve dinlenme faaliyetlerime daha az öncelik veririm.",
    "Eş veya aile üyelerini sosyal medyadan dolayı ihmal ettiğim olur.",
    "Arkadaşlarımı sosyal medyadan dolayı ihmal ettiğim olur.",
    "Sosyal medya dolayısıyla başladığım aktiviteleri zamanında bitiremem.",
    "Sosyal medya dolayısıyla daha fazla zaman geçirmek için okula veya işle ilgili çalışmaları ihmal ederim.",
    "Sosyal medyada zaman geçirmeyi arkadaşlarımla zaman geçirmeye tercih ederim.",
    "Sosyal medyada geçirdiğim zaman yüzünden okul çalışmalarım ya da işlerim sekteye uğrar.",
    "Sosyal medya yüzünden üretkenliğim azalır.",
    "Sosyal medyada zaman geçirmeyi arkadaşlarımla zaman geçirmeyi tercih ederim.",
    "İnsanlar sosyal medyada geçirdiğim zamanın miktarı konusunda beni eleştirirler.",
    "Kendimi sosyal medyada ne kadar süre gezindiğimi saklamaya çalışırken bulurum.",
    "Sosyal medya yüzünden yemek yemeyi unuttuğum zamanlar olur.",
    "Sosyal medya kullanımı yüzünden kişisel bakımıma daha az vakit ayırdığım olur.",
    "Sosyal medya kullanımı yüzünden uyku düzenimde değişiklikler/bozukluklar olur.",
    "Sosyal medya kullanımı yüzünden fiziksel sorunlar (sırt, baş, göz, ağrıları vb.) yaşadığım olur.",
    "Sosyal medya kullanımı benim için önemli kişilerle olan ilişkilerimde problem yaşamama neden olur.",
    "Sosyal medya kullanımının yaşamımda sorunlar oluşturur.",
    "Yapmam gereken işler çoğaldıkça, sosyal medya kullanma isteğim de ölçüde artar."
];