const SOCIAL_MEDIA_SPENT_TIME_CHECK_INTERVAL = 600000;
const DAILY_LIMIT_EXCESSION_AMOUNT = 1800;
const Q_LEARNING_WEIGHT_VECTOR_COEFFICIENT = 0.8;
const MAX_GRADE_INTERVAL = 10
const MIN_GRADE_INTERVAL = -10

export {
  SOCIAL_MEDIA_SPENT_TIME_CHECK_INTERVAL,
  DAILY_LIMIT_EXCESSION_AMOUNT,
  Q_LEARNING_WEIGHT_VECTOR_COEFFICIENT,
  MAX_GRADE_INTERVAL,
  MIN_GRADE_INTERVAL
};
