const SOCIAL_MEDIA_SPENT_TIME_CHECK_INTERVAL = 600000;
const DAILY_LIMIT_EXCESSION_AMOUNT = 1800;
const Q_LEARNING_WEIGHT_VECTOR_COEFFICIENT = 0.8;
const MAX_GRADE_INTERVAL = 10;
const MIN_GRADE_INTERVAL = -10;
const APP_NAME = "diDENGE";
const CLEAR_ALL_NOTIFICATION_INTERVAL = 10000;
const PUSH_NOTIFICATION_INTERVAL = 2000;
const FIRST_PIECE_OF_USER_DAILY_LIMIT_INTERVAL_DIVISION_AMOUNT = 5;
const SECOND_PIECE_OF_USER_DAILY_LIMIT_INTERVAL_DIVISION_AMOUNT = 10;

const getHalfOfUserDailyLimit = (userDailyLimit) => userDailyLimit / 2;
const getFirstPieceOfUserDailyLimitInterval = (userDailyLimit) =>
  getHalfOfUserDailyLimit(userDailyLimit) /
  FIRST_PIECE_OF_USER_DAILY_LIMIT_INTERVAL_DIVISION_AMOUNT;
const getSecondPieceOfUserDailyLimitInterval = (userDailyLimit) =>
  getHalfOfUserDailyLimit(userDailyLimit) /
  SECOND_PIECE_OF_USER_DAILY_LIMIT_INTERVAL_DIVISION_AMOUNT;

export {
  SOCIAL_MEDIA_SPENT_TIME_CHECK_INTERVAL,
  DAILY_LIMIT_EXCESSION_AMOUNT,
  Q_LEARNING_WEIGHT_VECTOR_COEFFICIENT,
  MAX_GRADE_INTERVAL,
  MIN_GRADE_INTERVAL,
  APP_NAME,
  CLEAR_ALL_NOTIFICATION_INTERVAL,
  PUSH_NOTIFICATION_INTERVAL,
  getFirstPieceOfUserDailyLimitInterval,
  getSecondPieceOfUserDailyLimitInterval,
};
