const PROCEDURE_POINT_INFORMATION = "procedurePointInformation";
const SOCIAL_MEDIA_APPLICATION_USAGES = "socialMediaApplicationUsages";

export { PROCEDURE_POINT_INFORMATION, SOCIAL_MEDIA_APPLICATION_USAGES };
